ecosystem {
    enforce_permissions = false
    no_update_news = true
    no_donation_nag = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

cursor {
    no_warps = true
    no_hardware_cursors = true
}

# Enable all connected monitors with preferred resolution
monitor = ,preferred,auto,1
